# Generated by Django 5.0.2 on 2024-03-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
