# Generated by Django 5.0.2 on 2024-03-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(default='default.png', null=True, upload_to='course_pic/%y/%m/%d/'),
        ),
    ]
